apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: namegame-statistics-deploy
spec:
  replicas: 1
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: namegame-statistics
    spec:
      containers:
      - name: namegame-statistics-pod
        image: ritambanik/namegame-statistics
        env:
        - name: MONGODB_HOST
          value: mongodb
        ports:
        - containerPort: 8083
