apiVersion: v1
kind: Service
metadata:
  name: namegame-statistics-svc
  labels:
    app: namegame-statistics
spec:
  type: NodePort
  ports:
  - port: 8083
    nodePort: 30002
  selector:
    app: namegame-statistics
