spring:
  application:
    name: namegame-statistics
  data:
    mongodb:
      host: namegame-db-mongodb
      ##host: localhost -- for connecting to local MongoDB instance or if the app is running outside minikube and MongoDB inside minikube with port forwarding
      port: 27017
      database: namegame-db
      username: namegame
      password: willowtree

server:
  port: 8083
  servlet:
    context-path: /namegame

logging:
  level:
    root: DEBUG
    com.willowtree.test.statistics: INFO

namegame-statistics:
  default:
    countOfLeaders: 10
